# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'fignest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fignest
  pod 'FBSDKLoginKit', '~> 4.13'
  pod 'FBSDKCoreKit', '~> 4.13'
  pod 'Socket.IO-Client-Swift', '~> 6.1'
  pod 'Alamofire', '~> 3.4'

  target 'fignestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fignestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
